#!/usr/bin/env bash
# This script transfers a file from a client to a server using scp

# Check if correct number of parameters is provided
if [ "$#" -ne 4 ]; then
    echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
    exit 1
fi

# Assign parameters to variables
FILE_PATH="$1"
SERVER_IP="$2"
USERNAME="$3"
SSH_KEY_PATH="$4"

# Transfer the file to the user's home directory on the server
scp -o StrictHostKeyChecking=no -i "$SSH_KEY_PATH" "$FILE_PATH" "$USERNAME"@"$SERVER_IP":~/ 

