#!/usr/bin/env bash
# Manages the script manage_my_process.
#   When passed the argument `start`:
#     1. Starts manage_my_process
#     2. Creates a file containing its PID in /var/run/my_process.pid
#     3. Displays "manage_my_process started"
#   When passed the argument `stop`:
#     1. Stops manage_my_process
#     2. Deletes the file /var/run/my_process.pid
#     3. Displays "manage_my_process stopped"
#   When passed the argument `restart`:
#     1. Stops manage_my_process
#     2. Deletes the file /var/run/my_process.pid
#     3. Starts manage_my_process
#     4. Creates a file containing its PID in /var/run/my_process.pid
#     5. Displays "manage_my_process restarted"
#   If any other or no arguments are passed, displays
#+  "Usage: manage_my_process {start|stop|restart}"

PIDFILE=/var/run/my_process.pid
MANAGE_SCRIPT="./manage_my_process"

start() {
  if [ -e "$PIDFILE" ]; then
    echo "manage_my_process is already running. Remove $PIDFILE if it's not."
  else
    "$MANAGE_SCRIPT" &
    echo "$!" > "$PIDFILE"
    echo "manage_my_process started"
  fi
}

stop() {
  if [ -e "$PIDFILE" ]; then
    kill "$(cat "$PIDFILE")"
    rm -f "$PIDFILE"
    echo "manage_my_process stopped"
  else
    echo "manage_my_process is not running (no PID file found)."
  fi
}

restart() {
  stop
  start
  echo "manage_my_process restarted"
}

case "$1" in
  start)
    start
    ;;
  stop)
    stop
    ;;
  restart)
    restart
    ;;
  *)
    echo "Usage: $0 {start|stop|restart}"
    exit 1
    ;;
esac

exit 0
